version: '2.28.1'

services:
  pse-proxy:
    image: invisirisk/pse:v1.0.3
    container_name: pse-proxy
    user: root
    environment:
      - INVISIRISK_JWT_TOKEN="123"
      - PSE_DEBUG_FLAG=--alsologtostderr
      - POLICY_LOG=t
      - INVISIRISK_PORTAL=https://app.a.invisirisk.com/
  build-service-1:
    image: python:3.10-alpine
    container_name: build-service-1
    user: root
    cap_add:
      - NET_ADMIN
    depends_on:
      - pse-proxy
    environment:
      - SERVICE_NAME=build-service-1
      - TECHNOLOGY=python
      - VERSION=3.10
      - MANIFEST_FILE=requirements.txt
      - BUILD_ID=715ca371-d273-4494-8ba9-c0d84b63eb58
    volumes:
      - ./entrypoints:/app/entrypoints
      - requirements.txt:/app/requirements.txt
      - ./build.sh:/app/build.sh
    working_dir: /app
    entrypoint: ["/app/entrypoints/entrypoint.sh"]