name: Python packages 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  checks: write
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      pse:
        image: kkisalaya/pse-proxy:dev
        env:
          PSE_DEBUG_FLAG: --alsologtostderr
          POLICY_LOG: t
          INVISIRISK_JWT_TOKEN: WkxFvX05QDdcVUbN4AQPFNKVUo91hPpicvDitZL3RoJGEeKzzOSGaKXMeC34nEJbehBsxlT5DMF_RZ8-RQ1Lhg
          INVISIRISK_PORTAL: https://app.dev.veribom.com/
          #POLICY_AUTH_TOKEN: ${{ secrets.POLICY_AUTH_TOKEN }}
          #POLICY_URL: https://app.dev.veribom.com/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: python:3.10-alpine
      options: --cap-add=NET_ADMIN
    steps:
    - uses: invisirisk/pse-action@v1.0.7
      with:
          SCAN_ID: 'Dummy scan id'
          github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
   
